name: sample_flutter

packages:
  - '**'

scripts:
  analyze:
    exec: fvm flutter analyze .
  build:
    exec: fvm flutter packages pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  get:
    exec: fvm flutter pub get